### ISSUE TITLE
Wildcard search is not working as expected with uppercase field values

### ISSUE THREAD

**Issue by mjr5749** [Graylog2/graylog2-web-interface#672] opened 2014-02-26 20:48 UTC
I have messages with fields in the following structure:
```
"tx_name": "VIEW_TROUBLE_TICKETING_GET_TROUBLE_TICKET"
```

When I try a wild-card search in the Graylog web interface , Graylog submits the following query that returns no results:

```
"query": {
    "query_string": {
        "query": "tx_name:VIEW*",
        "allow_leading_wildcard": false
    }
}
```

If I add the lowercase_expanded_terms attribute to this search and submit it directly to ElasticSearch, it returns the results I am looking for:

```
"query": {
    "query_string": {
        "query": "tx_name:VIEW*",
        "allow_leading_wildcard": false,
        "lowercase_expanded_terms":false
    }
}
```

It seems that the best practice might be to lowercase as many fields as possible when storing them in Graylog.  (??)

If these types of searches cannot be supported, it would be helpful to describe this limitation in the search bar documentation:
http://support.torch.sh/help/kb/graylog2-web-interface/the-search-bar-explained

**Comment by darraghjones** [comment] 2015-02-03 13:11
Wait? So not being able to execute a wildcard search is by design?

**Comment by kubanczyk** [comment] 2015-03-15 01:09
This seems a simple issue, because there is a weird but simple workaround. In Quickfilter field Message, just enter   `VIEW* VIEW*`   instead of `VIEW*` and voila, it matches view, VieW, and VIEW. After any wildcard expression, just put a space, and the same expression again.

**Comment by darraghjones** [comment] 2015-05-21 11:50
Surely that's just the same as searching for VIEW* and ignoring the tx_name: field altogether?

**Comment by kubanczyk** [comment] 2015-05-24 06:46
I've checked on my old graylog2-0.9.6p1 that `VIEW* VIEW*` doesn't work the same as single `VIEW*`. Note that this is/was an old issue from before 0.20.2. I've checked that 1.0.2 doesn't show this weirdness, so the issue should be closed.

**Comment by joschi** [comment] 2015-05-24 09:00
Thanks for the update. I'm closing this issue. Please add a comment if there are still problems with this in the latest versions of Graylog.

**Closed by joschi** 2015-05-24 09:00 UTC

**Comment by zolech** [comment] 2015-08-27 09:21
Same problem here. Graylog 1.1.6

Searching pattern field: *PL123456* returns nothing however field: *123456* works ok.
