### ISSUE TITLE
Read users aren't able to export search results as CSV

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-web-interface#1492] opened 2015-06-17 12:25 UTC
Non-admin users who try to export messages of a stream as CSV, only get a JSON document with the following content:
```
{"type":"ApiError","message":"HTTP 403 Forbidden"}
```

Refs #1478

**Comment by Binford3000** [comment] 2015-06-23 09:52
With 1.1.3 I get an error with "Invalid range type provided." as the reason. Only as "read" user. Admin is working. Do you need any more information?


Request information:

Method
    GET
Query

        relative=300
        sortField=timestamp
        q=54bfbb5d0cf2b56ecadd2bf4?rangetype=relativeTrk*
        fields=message,source
        sortOrder=desc

Referer
    https://<HOSTNAME>:1443/streams/54bfbb5d0cf2b56ecadd2bf4/messages?rangetype=relative&fields=message%2Csource&width=1883&relative=300&q=Trk*
Connection
    keep-alive
Accept
    text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
DNT
    1
Accept-Language
    de,en-US;q=0.7,en;q=0.3
Accept-Encoding
    gzip, deflate
User-Agent
    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Host
    <HOSTNAME>:1443

**Comment by edmundoa** [comment] 2015-06-23 11:28
I could reproduce the behaviour @Binford3000 described in 1.1.3 and master.

**Comment by edmundoa** [comment] 2015-06-23 11:30
I thought it's better to create a new issue for tracking this, closing this one again :)

**Closed by edmundoa** 2015-06-23 11:30 UTC
Labels: bug
