### ISSUE TITLE
Alarm callback boolean configs are not displayed

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1443] opened 2015-06-05 23:16 UTC
There should be a true/false value but it is empty:

![screen shot 2015-06-05 at 6 15 44 pm](https://cloud.githubusercontent.com/assets/35022/8016863/f64d616e-0bae-11e5-8fa5-3865416abfd3.png)

**Comment by dennisoelkers** [comment] 2015-06-08 08:42
This is supposed to be fixed in 24718cb9253782f63207b3e6f7e3f04b09bfd0dd. Which version did you use?

**Comment by dennisoelkers** [comment] 2015-06-08 09:08
Just tested this with the most recent state of 1.1 and it looks like this for the Jabber plugin:

![screen shot 2015-06-08 at 11 07 15](https://cloud.githubusercontent.com/assets/41929/8031444/8ed686f6-0dce-11e5-96f4-44be8bab5776.png)

Which plugin did you use? How can I reproduce this?

**Comment by dennisoelkers** [comment] 2015-06-09 09:15
Closing for now, please reopen if it still persists.

**Closed by dennisoelkers** 2015-06-09 09:15 UTC
