### ISSUE TITLE
Unable to set custom startpage for admin user

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#467] opened 2014-01-12 15:10 UTC
The admin user is read-only, so it cannot accept any change user requests.

This is one of the reasons I didn't want to extend the user model for UI related things, but rather have a preference collection alongside.
We'll need to clean this up post-0.20.0.

**Comment by edmundoa** [comment] 2015-03-02 16:55
I'm closing this in favour of #861. In the end the issue is the same: the admin user is hard-coded into Graylog server and not editable.

**Closed by edmundoa** 2015-03-02 16:55 UTC
Labels: users
