### ISSUE TITLE
Web interface crashes hard on REST timeout

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1126] opened 2015-02-14 01:08 UTC
I ran into a REST timeout of the `graylog-server` REST API and the web interface crashed:

```
[error] o.g.r.l.ApiClient - REST call failed
java.util.concurrent.TimeoutException: No response received after 5000
	at com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260) ~[async-http-client-1.8.14.jar:na]
	at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:433) ~[graylog2-rest-client-1.1.0-SNAPSHOT.jar:na]
	at org.graylog2.restclient.models.StreamService.get(StreamService.java:86) [graylog2-rest-client-1.1.0-SNAPSHOT.jar:na]
	at controllers.api.SystemApiController.streamThroughput(SystemApiController.java:158) [classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$137$$anonfun$apply$773.apply(routes_routing.scala:2421) [classes/:na]
[error] o.g.r.l.ApiClient - unhandled IOException
java.io.IOException: Closed
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:990) ~[async-http-client-1.8.14.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:938) ~[async-http-client-1.8.14.jar:na]
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499) ~[async-http-client-1.8.14.jar:na]
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:229) ~[async-http-client-1.8.14.jar:na]
	at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:433) ~[graylog2-rest-client-1.1.0-SNAPSHOT.jar:na]
lennart ~/workspace/graylog2/graylog2-web-interface(ux)$
```

Branch `ux` is pretty much the current master + a few frontend commtis.

**Comment by joschi** [comment] 2015-02-15 15:27
I'm unable to reproduce this with current master and the 1.0 branch. Could
you please check whether the problem also occurs in those branches on your
machine?

**Comment by joschi** [comment] 2015-02-17 09:25
The problem couldn't be reproduced. I'm closing this issue for now, please reopen if the error happens again.

**Closed by joschi** 2015-02-17 09:25 UTC
