### ISSUE TITLE
Follow up for #1554 - Requesting HTTP Header set X-UA-Compatible value to address Internet Explorer Compatibility Mode

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/graylog2-web-interface#1661] opened 2015-10-26 15:08 UTC
Originally this article https://msdn.microsoft.com/en-us/library/ff955275(v=vs.85).aspx indicated that this value could be set in the <head> section of the HTML page, but this doesn't work as expected.

Currently IE still uses compability mode for this page when hosted internally.

Adding this value to the HTTP header as indicated here, should address this:
http://stackoverflow.com/questions/6156639/x-ua-compatible-is-set-to-ie-edge-but-it-still-doesnt-stop-compatibility-mode

**Comment by joschi** [comment] 2015-10-26 15:22
Which version of IE are you using exactly?

**Comment by drewmmiranda** [comment] 2015-10-29 02:28
Tested primarily in IE9 but the behavior is not specific to IE9 and can occur in 8-11. The issue is that IE by default loads local intranet sites (e.g. graylog.localdomain.tld) with compatibility view enabled which causes the pages to load with IE view mode as version 7. By setting the http header to that version, it forces the pages loaded, even if part of local intranet zone. I have verified this on other local intranet sites where I can control the http header values (e.g. IIS)

**Comment by Gamesh** [comment] 2015-10-29 11:09
is there a way to add a custom header that would be served with every graylog web page?
where and how do you do it? we have the same problem and need to add 
```X-UA-Compatible: "IE=edge,chrome=1"```
header

**Comment by kroepke** [comment] 2015-10-29 12:03
Not yet, but we'll consider this, or a related fix, for 1.3.

Thanks!

**Comment by Gamesh** [comment] 2015-10-29 14:48
i thinks you can close this issue as it is duplicate of and was already solved by  #1554

**Comment by Gamesh** [comment] 2015-10-29 14:50
also note that it's better to serve ie=edge as a server header instead of meta tag, because it causes IE to reload the page
as stated here https://github.com/google/web-starter-kit/issues/728

**Comment by drewmmiranda** [comment] 2015-10-30 03:27
This isn't a duplicate because #1554 isn't solved which is why I opened this issue.

**Comment by Gamesh** [comment] 2015-10-30 06:17
must be because the meta tag is not the top  most tag in the header, it must come as early as the charset meta tag and since it is the last tag in the header the IE does not switch rendering engine.
But i agree serving it as a http header would be far more better solution.
The fast quick fix would be to just move both meta before the <title> tag.

**Comment by edmundoa** [comment] 2015-11-03 10:38
This issue was fixed on #1668.

**Closed by edmundoa** 2015-11-03 10:38 UTC
