### ISSUE TITLE
Page design on "Alert callbacks" page needs improvement 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1259] opened 2015-05-06 13:21 UTC
`graylog-web-interface-1.1.0-SNAPSHOT-20150506101534.tgz` 

"edit" and "delete" button are overlapping. Also the page is still using the old design.

![bildschirmfoto 2015-05-06 um 15 09 07](https://cloud.githubusercontent.com/assets/6331205/7493577/7070a7c2-f402-11e4-9e34-d75254162f28.png)

**Comment by bernd** [comment] 2015-05-06 16:24
Assigned to @dennisoelkers because he is currently working on the alert callback pages.

**Comment by dennisoelkers** [comment] 2015-05-13 14:12
Duplicate of #1217

**Closed by dennisoelkers** 2015-05-13 14:12 UTC
Labels: ux
