### ISSUE TITLE
Why is there no way to tail log messages in realtime in the web interface?

### ISSUE THREAD

**Issue by bymodude** [Graylog2/graylog2-web-interface#1640] opened 2015-10-12 14:42 UTC
I saw this: https://github.com/Graylog2/graylog2-stream-dashboard

But why is that not part of the main web interface? This is a huge omission in my oppinion.

**Comment by joschi** [comment] 2015-10-12 14:50
Duplicate of #133.

**Closed by joschi** 2015-10-12 14:50 UTC
