### ISSUE TITLE
LDAP password is "visible" in settings

### ISSUE THREAD

**Issue by beezoncheg** [Graylog2/graylog2-web-interface#1597] opened 2015-09-07 22:56 UTC
Password can be seen in source code of LDAP settings page in browser. I think it's a bad idea to send it back to browser.

**Comment by joschi** [comment] 2015-09-08 09:22
Thanks for reporting this!

It's basically a duplicate of Graylog2/graylog2-server#1087 which is why I will close this issue.

**Closed by joschi** 2015-09-08 09:22 UTC

**Comment by kroepke** [comment] 2015-09-08 09:24
Another comment: Since this is a breaking API change, which would also affect alarm callbacks, output plugins and potentially inputs, we have to postpone the change to 2.0 for stability reasons.

We do agree that it should be changed though :+1:
