### ISSUE TITLE
Google Apps Login?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#1087] opened 2015-01-27 12:24 UTC
Hi,

Is it possible to add Google Apps Login support? We are hosting all our business mail with Google and would like one login system :)

**Comment by kroepke** [comment] 2015-01-30 09:42
I don't believe that oauth works without setting a specific redirect url for google.
Essentially it would require you to register your own graylog instance as a google app, which I can't believe users really want to do.

Since graylog is hosted on premise, I see no way of doing this, unfortunately (same goes for any other oauth provider).

**Comment by edmundoa** [comment] 2015-02-10 16:24
Duplicate of #730

**Closed by edmundoa** 2015-02-10 16:24 UTC
