### ISSUE TITLE
Apply Extractors retrospectively

### ISSUE THREAD

**Issue by Crystalh** [Graylog2/graylog2-web-interface#784] opened 2014-05-21 21:31 UTC
The ability to apply Extractors retrospectively to a given data set would be very helpful. It's easy to forget to set up all your extractors, or even know what will necessarily be useful, in advance of writing log packets.

**Comment by brushwood24** [comment] 2015-05-27 16:34
+1

**Comment by bernd** [comment] 2015-08-11 16:16
Duplicate of Graylog2/graylog2-server#736.

**Closed by bernd** 2015-08-11 16:16 UTC
Labels: extractors
