### ISSUE TITLE
Stream email alert includes messages of the wrong stream

### ISSUE THREAD

**Issue by plista-ld** [Graylog2/graylog2-web-interface#1187] opened 2015-03-25 21:36 UTC
I have set up an alert on the elasticsearch stream (rule -> facility = elasticsearch) to send alerts when the minimum level value is lower than 5. The alert email should include the last 3 messages accounting for this alert.

The alert works fine, but the message included in the email do not belong to the elasticsearch stream. They belong to another stream that get lots of messages per second (haproxy access logs).

I could reproduce the error.

**Comment by dennisoelkers** [comment] 2015-05-21 13:02
Duplicate of Graylog2/graylog2-server#1153. Has been fixed and will be included in 1.1.0 (the beta was just released yesterday) and a potential 1.0.3 that might be released very soon.

**Closed by dennisoelkers** 2015-05-21 13:02 UTC
