### ISSUE TITLE
Probleme deleting Streams, Users 

### ISSUE THREAD

**Issue by mindenchanter** [Graylog2/graylog2-web-interface#1514] opened 2015-07-06 16:36 UTC
When I try to delete Stream or user I see an error message of this type and no more.

Could not delete Stream Rule
Deleting Stream Rule failed with status:

![gray_log_error](https://cloud.githubusercontent.com/assets/13204614/8527595/11ddbabc-2416-11e5-9929-ad233b06d547.png)
 
In grayserver log I didn't find anyhink about this error. It is a bug or I do something wrong?

**Comment by mindenchanter** [comment] 2015-07-07 17:53
Supplementary I check application.log and no error messages. And I cannot delete Notification too. But I can create and delete dashboard.

**Comment by edmundoa** [comment] 2015-07-13 08:49
Hi,

It's really hard to know the cause of this without any more information. Could you please share any log messages from the Graylog server or web interface that appear while you delete the stream rule? It would also be really helpful if you keep your browser's developer tools open while trying to delete the stream rule and share any errors you may see.

**Comment by edmundoa** [comment] 2015-07-20 09:41
Hi @mindenchanter,

Any updates on this?

**Comment by edmundoa** [comment] 2015-07-23 12:22
Closing the issue, as we haven't any more information. Please reopen if needed.

**Closed by edmundoa** 2015-07-23 12:22 UTC

**Comment by unamuno** [comment] 2016-01-20 12:07
Hi, I have the same problem. I can't delete anyting. There are realy no logs when this happens. Not in the graylog-server.log, ../web/application.log, ../web/console.log, mongod.log. 

I tried to delete a user manualy from the mongodb, but it still remains in the Web GUI even after restarting the service.

Are there any other ways to get more information?

**Comment by unamuno** [comment] 2016-01-20 12:22
I found an error in the debug console of my browser: ERR_EMPTY_RESPONSE

jquery-2.1.1.min.js:4 DELETE https://$HOST$/a/dashboards/569f6518e4b0e5b7a620e22c net::ERR_EMPTY_RESPONSEk.cors.a.crossDomain.send @ jquery-2.1.1.min.js:4n.extend.ajax @ jquery-2.1.1.min.js:4e.remove @ app.6522837….js:28a.default.createClass._onDashboardDelete @ app.6522837….js:438(anonymous function) @ app.6522837….js:22o.default.createClass.handleClick @ app.6522837….js:436s @ app.6522837….js:30M.executeDispatch @ app.6522837….js:446o @ app.6522837….js:30u @ app.6522837….js:30d @ app.6522837….js:28n @ app.6522837….js:30p.processEventQueue @ app.6522837….js:28r @ app.6522837….js:446a.handleTopLevel @ app.6522837….js:446a @ app.6522837….js:446i.perform @ app.6522837….js:29f.batchedUpdates @ app.6522837….js:445a @ app.6522837….js:21g.dispatchEvent @ app.6522837….js:446
