### ISSUE TITLE
Alarm callback list has overflow issue

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1439] opened 2015-06-05 22:42 UTC
![screen shot 2015-06-05 at 5 41 34 pm](https://cloud.githubusercontent.com/assets/35022/8016548/4fb916c6-0baa-11e5-9e84-1f4fe31a5d2d.png)

**Comment by dennisoelkers** [comment] 2015-06-09 08:39
Which browser are you using? I am unable to reproduce that.

**Comment by dennisoelkers** [comment] 2015-06-09 09:13
After talking to @edmundoa it seems like this has been fixed in 24718cb9253782f63207b3e6f7e3f04b09bfd0dd meanwhile.

**Closed by dennisoelkers** 2015-06-09 09:13 UTC
