### ISSUE TITLE
Add Extractor page display issue

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#1686] opened 2015-11-12 14:26 UTC
After upgrading to v1.2.2 the full_message field is no longer displayed correctly - instead the page only shows "full_message [object Object]"

**Comment by joschi** [comment] 2015-11-16 14:46
Unfortunately (or rather fortunately) I can't reproduce this on Graylog 1.2.2.

@henrikjohansen Is the `full_message` field only invalid in some cases or all the time? Are those messages correctly stored in Elasticsearch, including a valid `full_message` document field?
Maybe some external GELF client already transmits those invalid contents ("[object Object]", which looks like the JavaScript notation of a stringified complex object).

**Comment by henrikjohansen** [comment] 2015-11-17 07:37
@joschi the full_message field is present and can also be selected as a field to run extractors against - it's merely a display issue.

![screenshot from 2015-11-17 08-37-03](https://cloud.githubusercontent.com/assets/1473308/11205229/69c19f56-8d06-11e5-92a6-2b199ba2be4d.png)

**Comment by joschi** [comment] 2015-11-17 09:45
@henrikjohansen Ah, ok. It seems only to happen on the Extractor page. I've tried to reproduce the bug on the search page and on the streams page.

**Comment by edmundoa** [comment] 2015-11-25 17:21
This was fixed in the linked PRs, and also on master.

**Closed by edmundoa** 2015-11-25 17:21 UTC
Labels: bug, extractors
