### ISSUE TITLE
CSV Export fails with invalid enum type

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1506] opened 2015-06-25 09:01 UTC
reported by a user:
running 1.1.x
```
Fehlermeldung:

Oh no, something went wrong!

(You caused a java.lang.IllegalArgumentException. No enum constant org.graylog2.restclient.lib.timeranges.TimeRange.Type.)

Reason: Invalid range type provided. 
Need help? 
Do not hesitate to consult the Graylog community if your questions are not answered in the documentation<http://docs.graylog.org/>.

* Forum / Mailing list<https://www.graylog.org/community-support/> 
* Issue tracker<https://github.com/Graylog2/graylog2-web-interface/issues> 
* Commercial support<https://www.graylog.com/support/>

Stacktrace

* java.lang.Enum#valueOf (Enum.java:238) 
* org.graylog2.restclient.lib.timeranges.TimeRange$Type#valueOf (TimeRange.java:23) 
* org.graylog2.restclient.lib.timeranges.TimeRange#factory (TimeRange.java:43) 
* controllers.SearchController#getSearch (SearchController.java:475) 
* controllers.SearchController#exportAsCsv (SearchController.java:421) 
* controllers.StreamSearchController#exportAsCsv (StreamSearchController.java:59) 
* Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$516#apply (routes_routing.scala:1811) 
* Routes$$anonfun$routes$1$$anonfun$applyOrElse$26$$anonfun$apply$516#apply (routes_routing.scala:1811) 
* play.core.Router$HandlerInvokerFactory$$anon$4#resultCall (Router.scala:264) 
* play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#invocation (Router.scala:255) 
* play.core.j.JavaAction$$anon$1#call (JavaAction.scala:55) 
* play.GlobalSettings$1#call (GlobalSettings.java:67) 
* play.mvc.Security$AuthenticatedAction#call (Security.java:44) 
* play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82) 
* play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82) 
* scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24) 
* scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24) 
* play.core.j.HttpExecutionContext$$anon$2#run (HttpExecutionContext.scala:40) 
* play.api.libs.iteratee.Execution$trampoline$#execute (Execution.scala:46) 
* play.core.j.HttpExecutionContext#execute (HttpExecutionContext.scala:32) 
* scala.concurrent.impl.Future$#apply (Future.scala:31) 
* scala.concurrent.Future$#apply (Future.scala:485) 
* play.core.j.JavaAction$class#apply (JavaAction.scala:82) 
* play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#apply (Router.scala:252) 
* play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130) 
* play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130) 
* play.utils.Threads$#withContextClassLoader (Threads.scala:21) 
* play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:129) 
* play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:128) 
* scala.Option#map (Option.scala:145) 
* play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:128) 
* play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:121) 
* play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483) 
* play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483) 
* play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519) 
* play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519) 
* play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496) 
* play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496) 
* scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24) 
* scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24) 
* akka.dispatch.TaskInvocation#run (AbstractDispatcher.scala:41) 
* akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask#exec (AbstractDispatcher.scala:393) 
* scala.concurrent.forkjoin.ForkJoinTask#doExec (ForkJoinTask.java:260) 
* scala.concurrent.forkjoin.ForkJoinPool$WorkQueue#runTask (ForkJoinPool.java:1339) 
* scala.concurrent.forkjoin.ForkJoinPool#runWorker (ForkJoinPool.java:1979) 
* scala.concurrent.forkjoin.ForkJoinWorkerThread#run (ForkJoinWorkerThread.java:107)

Request information 
Method 
GET 
Query 
· relative=1209600 
· sortField=dst 
· q=5420224617f0398625dd3943?rangetype=relativesource:fw-etdc-het* AND dst_port:102 
· fields=source,dst,dst_port,dst_zone,reason,src 
· sortOrder=asc 
Referer 
https://graylog.xxxxx/streams/5420224617f0398625dd3943/messages?rangetype=relative&relative=1209600&q=source%3Afw-etdc-het*%20AND%20dst_port%3A102&page=3&fields=source%2Cdst%2Cdst_port%2Cdst_zone%2Creason%2Csrc&sortField=dst&sortOrder=asc 

```

**Comment by joschi** [comment] 2015-06-25 09:02
Looks like the query is incorrectly build (the `q` query parameter contains the stream id and the range type):
```
Query 
* relative=1209600 
* sortField=dst 
* q=5420224617f0398625dd3943?rangetype=relativesource:fw-etdc-het* AND dst_port:102 
* fields=source,dst,dst_port,dst_zone,reason,src 
* sortOrder=asc
```

**Comment by joschi** [comment] 2015-06-25 09:15
Duplicate of #1504.

**Closed by joschi** 2015-06-25 09:15 UTC
