### ISSUE TITLE
Feature Request:World ip map

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog2-web-interface#1065] opened 2015-01-23 15:10 UTC
Hi all,
it's possible in feature version to have a world ip map not of log source address but of certain file (firewall logged session source ip?)

**Comment by runningman84** [comment] 2015-01-23 19:14
this is a duplicate of
https://github.com/Graylog2/graylog2-web-interface/issues/1001

**Closed** 2015-01-23 22:39 UTC
